# https://github.com/astral-sh/ruff-action?tab=readme-ov-file#basic
name: Ruff

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Ruff
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format